version: "3"
services:
  web:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/usr/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    command: ["npm", "run", "test"]
  prod:
    build: .
    ports:
      - 443:80
